
name: CI

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

  
  workflow_dispatch:
env:
  Greeting: Atisha'job

jobs:
 
  build:
    
    runs-on: ubuntu-latest

    
    steps:
     
      - uses: actions/checkout@v2

    
      - name: Run a one-line script
        run: echo Hello, world!

     
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  Display:
    
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: Display
    
    steps:
     
      - uses: actions/checkout@v2

    
      - name: Run a one-line script
        run: echo Hello, Atisha!

     
      
        
